### PR TITLE
Docs and dependencies version update

### PR DESCRIPTION
**Pull request by karlaspuldaro**
- Documentation update 
- Update lab3 dependencies to rc10

### CODE REVIEW

**Comment by karlaspuldaro** [comment]
@martinRenou Should I create a PR with these changes against `jupyterlab3_stable` branch instead?

**Comment by martinRenou** [comment]
Thank you for doing this!

> @martinRenou Should I create a PR with these changes against jupyterlab3_stable branch instead?

No, this "stable" branch is for internal use at my company, it contains other things that are not relevant to the PR I made for JupyterLab 3. Sorry for the confusion.

**Comment by martinRenou** [comment]
Let's merge it and see about the CI on the main repo (I am actually confused, the CI should not be triggered on my fork Oo)

**Comment by karlaspuldaro** [comment]
Thank you. I wasn't sure how to deal with the failing CI checks here. When you say it shouldn't be triggered on your fork, is that why your open PR only checks the read the docs build for now?

**Comment by martinRenou** [comment]
> is that why your open PR only checks the read the docs

This is odd. I recall Github actions being triggered Oo

**Pull request merged**
